version: 0.2

env:
  variables:
    BRANCH: echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed 's/branch\///g'

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12.x
    commands:
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_SOURCE_VERSION
      - echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed 's/branch\///g'
      - env
      - npm --version
      - npm install -g serverless
      - npm install serverless-offline --save-dev
      - sls plugin install -n serverless-python-requirements --stage $BRANCH
  post_build:
    commands:
      - sls deploy --stage $BRANCH --region eu-west-1 --verbose
  
