version: 0.2

# env:
#   variables:
#     BRANCH: `$(echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed 's/branch\///g')`

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12.x
    commands:
      - echo "$CODEBUILD_WEBHOOK_BASE_REF | $CODEBUILD_WEBHOOK_HEAD_REF | $CODEBUILD_WEBHOOK_TRIGGER | $CODEBUILD_SOURCE_VERSION"
      - BRANCH=$(echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed 's/branch\///g')
      - echo $BRANCH
      - env
      - npm --version
      - npm install -g serverless
      - npm install serverless-offline --save-dev
      - sls plugin install -n serverless-python-requirements --stage $BRANCH
  post_build:
    commands:
      - sls deploy --stage $BRANCH --region eu-west-1 --verbose
  
