version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12.x
    commands:
      - npm --version
      - npm install -g serverless
      - npm install serverless-offline --save-dev
      - sls plugin install -n serverless-python-requirements
      # # NodeJs12
      # - apt update -y
      # - apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
      # - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      # - apt -y install nodejs
      # /NodeJs12
  post_build:
    commands:
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_SOURCE_VERSION
      - serverless deploy --stage $CODEBUILD_SOURCE_VERSION --region eu-west-1 --verbose
  
